x-default-tabero-environment: &default-tabero-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - ACCEPT_EULA=Y
  - PRIVACY_CONSENT=Y
  - PYTHONUNBUFFERED=1

x-default-tabero-deploy: &default-tabero-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  tabero:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - DOCKER_TABERO_PATH_ARG=${DOCKER_TABERO_PATH}
    image: tabero-isaaclab
    container_name: tabero-isaaclab
    volumes:
      - type: bind
        source: ../
        target: ${DOCKER_TABERO_PATH}
      - isaac-cache-kit:/isaac-sim/kit/cache:rw
      - isaac-cache-ov:/root/.cache/ov:rw
      - isaac-cache-pip:/root/.cache/pip:rw
      - isaac-cache-gl:/root/.cache/nvidia/GLCache:rw
      - isaac-cache-compute:/root/.nv/ComputeCache:rw
      - isaac-logs:/root/.nvidia-omniverse/logs:rw
      - isaac-data:/root/.local/share/ov/data:rw
      - isaac-docs:/root/Documents:rw
    network_mode: host
    environment: *default-tabero-environment
    deploy: *default-tabero-deploy
    entrypoint: bash
    stdin_open: true
    tty: true

volumes:
  isaac-cache-kit:
  isaac-cache-ov:
  isaac-cache-pip:
  isaac-cache-gl:
  isaac-cache-compute:
  isaac-logs:
  isaac-data:
  isaac-docs:
